/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproj.GUI.Staff;

import java.util.*;
import javaproj.Methods.Items.MedicationService;
import javaproj.Methods.Items.ServiceService;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author NICK
 */
public class AddItem extends javax.swing.JFrame {
    private final MedicationService medicationService = new MedicationService();
    private final ServiceService serviceService = new ServiceService();
    
    private final String selectedItem;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddItem.class.getName());
    
    //features
    private void updateCategory(String selectedItem){
        if (selectedItem == null) return;

        itemLabel.setText("Add " + selectedItem);
        List<String> items = new ArrayList<>();
        items.add("--- Select ---");

        if ("Medication".equalsIgnoreCase(selectedItem)) {
            items.addAll(medicationService.categories());   // therapeutic classes
        } else if ("Service".equalsIgnoreCase(selectedItem)) {
            items.addAll(serviceService.categories());       // service types
        }

        categoryComboBox.setModel(new DefaultComboBoxModel<>(items.toArray(new String[0])));
        categoryComboBox.setSelectedIndex(0);
    }
    private void addItem(String selectedItem){
        String name = nameInput.getText();
        String unitPriceText = unitPriceInput.getText().trim();
        String category = categoryComboBox.getSelectedItem().toString();
        String description = descriptionInput.getText();
        
        double unitPrice;
        
        if (name.trim().isEmpty() || name == null ) {
            JOptionPane.showMessageDialog(this, "Please enter item name.");
            return;
        }
        try {
            unitPrice = Double.parseDouble(unitPriceText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            return;
        }
        if (unitPrice < 0) {
            JOptionPane.showMessageDialog(this, "Unit Price cannot be negative.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (category == null || category.startsWith("---")) {
            JOptionPane.showMessageDialog(this, "Please select a category.");
            return;
        }
         try {
            if (selectedItem.equalsIgnoreCase("Medication")) {
                medicationService.addMedication(name, description, unitPrice, category);
            } else if (selectedItem.equalsIgnoreCase("Service")) {
                serviceService.addService(name, description, unitPrice, category);
            }
            JOptionPane.showMessageDialog(this, selectedItem + " added successfully.");
            dispose();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Add failed", ex);
            JOptionPane.showMessageDialog(this, "Failed to add " + selectedItem, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
    
    public AddItem(String selectedItem) {
        this.selectedItem = selectedItem;  
        initComponents();
        updateCategory(selectedItem);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        itemLabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        unitPriceInput = new javax.swing.JTextField();
        unitPrice = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        descriptionInput = new javax.swing.JTextField();
        description = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(245, 243, 238));

        itemLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemLabel.setForeground(java.awt.Color.black);
        itemLabel.setText("Add Item Label");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setForeground(java.awt.Color.black);
        name.setText("Name:");

        nameInput.setBackground(java.awt.Color.white);
        nameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameInput.setForeground(java.awt.Color.black);

        unitPriceInput.setBackground(java.awt.Color.white);
        unitPriceInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitPriceInput.setForeground(java.awt.Color.black);

        unitPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitPrice.setForeground(java.awt.Color.black);
        unitPrice.setText("Unit Price (RM):");

        category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        category.setForeground(java.awt.Color.black);
        category.setText("Category:");

        descriptionInput.setBackground(java.awt.Color.white);
        descriptionInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionInput.setForeground(java.awt.Color.black);

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setForeground(java.awt.Color.black);
        description.setText("Description:");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addGap(218, 218, 218))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(name)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(unitPrice)
                                    .addGap(18, 18, 18)
                                    .addComponent(unitPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(105, 105, 105))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(category)
                                    .addGap(18, 18, 18)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)))
                            .addComponent(itemLabel))
                        .addContainerGap(184, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(description)
                        .addGap(18, 18, 18)
                        .addComponent(descriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(itemLabel)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description))
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        addBtn.setName("contentSecondary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
         addItem(selectedItem);
         
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddItem("Service").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel category;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel description;
    private javax.swing.JTextField descriptionInput;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel unitPrice;
    private javax.swing.JTextField unitPriceInput;
    // End of variables declaration//GEN-END:variables
}
