package javaproj.GUI.Staff;

import javaproj.Model.Role.Customer;
import javaproj.Methods.User.CheckDuplicates;
import javaproj.Methods.User.CustomerService;

public class CreateAndEditCustomer extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAndEditCustomer.class.getName());
    private String id = null;
    private final CustomerService customerService = new CustomerService();
    private final CheckDuplicates checker = new CheckDuplicates();
    
    public CreateAndEditCustomer() {
        initComponents();
        jLabel2.setText("Add Customer");
    }
        
    public CreateAndEditCustomer(String id) {
        this.id = id;
        initComponents();
        jLabel2.setText("Edit Customer");

        Customer customer = customerService.getById(id);
        if (customer != null) {
            nameInput.setText(customer.getName());
            icInput.setText(customer.getIdentityNumber());
            addressInput.setText(customer.getAddress());
            phoneInput.setText(customer.getPhone());
            emailInput.setText(customer.getEmail());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        methodInput = new javax.swing.JLabel();
        icInput = new javax.swing.JTextField();
        patientic = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        methodInput2 = new javax.swing.JLabel();
        methodInput3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addressInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(245, 243, 238));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Edit Customer");

        amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amount.setForeground(java.awt.Color.black);
        amount.setText("Name:");

        nameInput.setBackground(java.awt.Color.white);
        nameInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameInput.setForeground(java.awt.Color.black);

        phoneInput.setBackground(java.awt.Color.white);
        phoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneInput.setForeground(java.awt.Color.black);

        methodInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodInput.setForeground(java.awt.Color.black);
        methodInput.setText("Phone:");

        icInput.setBackground(java.awt.Color.white);
        icInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        icInput.setForeground(java.awt.Color.black);

        patientic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        patientic.setForeground(java.awt.Color.black);
        patientic.setText("IC Number:");

        emailInput.setBackground(java.awt.Color.white);
        emailInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailInput.setForeground(java.awt.Color.black);

        methodInput2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodInput2.setForeground(java.awt.Color.black);
        methodInput2.setText("E-mail:");

        methodInput3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodInput3.setForeground(java.awt.Color.black);
        methodInput3.setText("Address:");

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addressInput.setColumns(20);
        addressInput.setLineWrap(true);
        addressInput.setRows(5);
        addressInput.setWrapStyleWord(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(amount)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(methodInput)
                                    .addGap(18, 18, 18)
                                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(methodInput2)
                                    .addGap(18, 18, 18)
                                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(patientic)
                                    .addGap(18, 18, 18)
                                    .addComponent(icInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(methodInput3)
                                .addGap(18, 18, 18)
                                .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 55, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(methodInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(methodInput2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(methodInput3)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jButton1.setName("contentSecondary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ic = icInput.getText();
        String name = nameInput.getText();
        String phone = phoneInput.getText();
        String email = emailInput.getText();
        String address = addressInput.getText();

        // Validate with CustomerService
        String error = customerService.validateForm(name, ic, address, phone, email);
        if (error != null) {
            javax.swing.JOptionPane.showMessageDialog(this, error, "Validation Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String dup = checker.checkDuplicates(id, ic, email);
        if (dup != null) {
            javax.swing.JOptionPane.showMessageDialog(this, dup, "Validation Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (id == null) {
            // Create
            customerService.create(name, ic, address, phone, email);
        } else {
            // Update
            boolean ok = customerService.update(id, name, ic, address, phone, email);
            if (!ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Update failed.");
                return;
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAndEditCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressInput;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField icInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel methodInput;
    private javax.swing.JLabel methodInput2;
    private javax.swing.JLabel methodInput3;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel patientic;
    private javax.swing.JTextField phoneInput;
    // End of variables declaration//GEN-END:variables
}
