package javaproj.GUI.Manager;

import java.util.Collections;
import javaproj.Model.Feedback;
import javaproj.Utils.*;
import javaproj.Methods.Feedback.ManagerFeedback;
import javaproj.Repository.FeedbackRepository;
import javaproj.Repository.AppointmentRepository;
import javaproj.Methods.User.CustomerService;

import java.util.List;
import java.util.stream.Collectors;
import javax.swing.*;
import javax.swing.table.*;
public class FeedbacknComment extends javax.swing.JPanel {
    // Service to get all feedback from storage
    private PanelController controller;
    
    ManagerFeedback managerFeedback = new ManagerFeedback(
            new FeedbackRepository(),
            new AppointmentRepository(),
            new CustomerService()
    );

    // List that hold all feedback data
    List<Feedback> feedbacks = managerFeedback .allFeedback();
    
    // Column names for the table
    String[] cols = {
            "Feedback ID", "Appointment ID", "User Type", "Rating",
            "Comment for doctor/from doctor", "Comment for staff"
        };
    // Table model, make cells not editable
    private DefaultTableModel model = new DefaultTableModel(cols, 0){
    @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public FeedbacknComment(PanelController controller) {
        this.controller = controller;
        model.setColumnIdentifiers(cols);   // Set the table header
        initComponents();
        initFilter();   // Build the drop down filter
        refreshTable(feedbacks);    // Fill table with all feedback first
        Utils.resizeColumnWidth(feedbackTable); // resize column for better view

    }
    
    // Reload table rows based on list given
    private void refreshTable(List<Feedback> list) {
        model.setRowCount(0);   // Clear all old rows
        Utils.refreshTable(feedbackTable, list, f -> new Object[]{
            f.getFeedbackId(),
            f.getAppointmentId(),
            f.getUserType(),
            f.getRating(),
            f.getComment1(),
            f.getComment2()
        });
    }
     
    // When filter applied, update header name and refresh table
    private void applyFilter() {
        String selected = (String) userTypeFilter.getSelectedItem();
        
        // Change the column header text for comment1 depending on filter choice
        TableColumnModel columnModel = feedbackTable.getColumnModel();
        TableColumn commentColumn = columnModel.getColumn(4); // column index 4 (5th column) = comment1 (from text file)

        if (selected.equalsIgnoreCase("Customer")) {
            commentColumn.setHeaderValue("Comment for doctor");
        } else if (selected.equalsIgnoreCase("Doctor")) {
            commentColumn.setHeaderValue("Comment for customer");
        } else {
            commentColumn.setHeaderValue("Comment for doctor/from doctor");
        }
        
        // Reload rows based on filter
        if (selected.equals("All")) {
            refreshTable(feedbacks);
        } else {
            refreshTable(feedbacks.stream()
                .filter(f -> f.getUserType().equalsIgnoreCase(selected))
                .collect(Collectors.toList()));
        }
        Utils.resizeColumnWidth(feedbackTable);
    }
    
    // Build the drop-down filter options
    private void initFilter() {
        // Collect distinct user types dynamically
        List<String> userTypes = feedbacks.stream()
                .map(Feedback::getUserType)
                .distinct()
                .collect(Collectors.toList());

        // Build a new model with "All" + user types
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("All");    // Always add "All" first
        for (String type : userTypes) {
            model.addElement(type);
        }

        // Replace the auto-generated model
        userTypeFilter.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        userTypeFilter = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(245, 243, 238));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setText("Feedback & Comment Review");

        jScrollPane1.setPreferredSize(null);

        feedbackTable.setModel(model);
        jScrollPane1.setViewportView(feedbackTable);

        userTypeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userTypeFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeFilterActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(707, 707, 707)
                        .addComponent(userTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userTypeFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeFilterActionPerformed
        // TODO add your handling code here:
        applyFilter();
    }//GEN-LAST:event_userTypeFilterActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        controller.show("home");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> userTypeFilter;
    // End of variables declaration//GEN-END:variables
}
