package javaproj.GUI.Manager;

import javaproj.Methods.Parser.AppointmentParser;
import javaproj.Model.Appointment;
import javaproj.Model.Role.Manager;
import javaproj.Utils.*;

import java.awt.*;
import javax.swing.*;
import java.util.List;
import javaproj.GUI.Credentials.LoginFrame;
import javaproj.GUI.Credentials.Session;
import javaproj.GUI.Common.*;
import javaproj.Model.Role.Supermanager;
import javaproj.Model.Role.User;
public class ManagerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerFrame.class.getName());

    private User loggedInManager;
    private CardLayout cardLayout;
    private JPanel contentPanel;

    // NAVBAR
    private HomePanel homePanel;
    private ProfilePanel profilePanel;
    private SettingPanel settingPanel;
    private AboutUsPanel aboutUsPanel;
    

    // HOME SUB-PANELS
    private UserManagementPanel userManagementPanel;
    private appointmentMonitoring appointmentMonitoringPanel;
    private FeedbacknComment feedbackncommentPanel;
    private reportPanel reportAnalysisPanel;
    
    // REPORT SUB-PANELS
    private appointmentReport appointmentReportPanel;
    private financialReport financialReportPanel;
    
    //String[] userinfo = {"M001","Mandev","123456781234","0182067277","Jalan Teknologi 5, Taman Teknologi Malaysia, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur","mandev@gmail.com","12345"};
    
    public ManagerFrame(Manager user) {
        
        this.loggedInManager = user;
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);
        
        setSize(1024,768);
        setLocationRelativeTo(null);

        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        PanelController controller = new PanelController(contentPanel);

        // NAVBAR PANELS
        homePanel = new HomePanel(controller,loggedInManager);
        profilePanel = new ProfilePanel();
        settingPanel = new SettingPanel();
        aboutUsPanel = new AboutUsPanel();
        
        contentPanel.add(homePanel, "home");
        contentPanel.add(profilePanel, "profile");
        contentPanel.add(settingPanel, "setting");
        contentPanel.add(aboutUsPanel, "aboutUs");

        // HOME PANELS
//        String currentUserId = loggedInManager.getSystemId();  // e.g. "S001" or "X001"
        userManagementPanel = new UserManagementPanel(controller, loggedInManager);
        appointmentMonitoringPanel = new appointmentMonitoring(controller);
        feedbackncommentPanel = new FeedbacknComment(controller);
        reportAnalysisPanel = new reportPanel(controller);
        
        contentPanel.add(userManagementPanel, "userManagementPanel");
        contentPanel.add(appointmentMonitoringPanel, "appointmentMonitoring");
        contentPanel.add(feedbackncommentPanel,"feedbackncomment");
        contentPanel.add(reportAnalysisPanel,"report");

        //REPORT PANEL BUTTON
        List<Appointment> appointments = Utils.readFile("data/appointment.txt", new AppointmentParser());
        appointmentReportPanel = new appointmentReport(controller); 
        
        contentPanel.add(appointmentReportPanel,"appointmentReport");
        
//        List<Payment> payments = Utils.readFile("data/payment.txt", new PaymentParser());
//        financialReportPanel = new financialReport(controller, payments);
        
        
        // Layout main window
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jPanel1, BorderLayout.NORTH);       // Top bar
        getContentPane().add(contentPanel, BorderLayout.CENTER); // Main content

        // Initial page
        cardLayout.show(contentPanel, "home");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        settingBtn = new javax.swing.JButton();
        aboutUsBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        pictureFormat1 = new javaproj.Comp.PictureFormat();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 243, 238));

        jPanel1.setBackground(new java.awt.Color(245, 243, 238));

        HomeBtn.setText("Home");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        settingBtn.setText("Setting");
        settingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingBtnActionPerformed(evt);
            }
        });

        aboutUsBtn.setText("About Us");
        aboutUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        pictureFormat1.set$image(new javax.swing.ImageIcon(getClass().getResource("/javaproj/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pictureFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(HomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(settingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(aboutUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {HomeBtn, aboutUsBtn, profileBtn, settingBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutUsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {HomeBtn, aboutUsBtn, profileBtn, settingBtn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 285, Short.MAX_VALUE))
        );

        jPanel1.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "home");
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void settingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "setting");
    }//GEN-LAST:event_settingBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "profile");
    }//GEN-LAST:event_profileBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        Session.clear();
        JFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void aboutUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsBtnActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "aboutUs");
    }//GEN-LAST:event_aboutUsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ManagerFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton aboutUsBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel jPanel1;
    private javaproj.Comp.PictureFormat pictureFormat1;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton settingBtn;
    // End of variables declaration//GEN-END:variables
}
