package javaproj.GUI.Customer;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import javaproj.GUI.Credentials.Session;
import javaproj.Model.Appointment;
import javaproj.Utils.PanelController;
import javaproj.Utils.Utils;
import javaproj.Repository.AppointmentRepository;
import javaproj.Methods.Appointment.CustomerAppointment;
import javaproj.Methods.User.DoctorService;
import javaproj.Model.Role.Doctor;
public class CancelAppointmentPanel extends javax.swing.JPanel {
    private PanelController controller;
    private final AppointmentRepository apptRepo = new AppointmentRepository();
    private final CustomerAppointment customerAppt = new CustomerAppointment(apptRepo);
    private final DoctorService doctorService = new DoctorService();
    
    public CancelAppointmentPanel(PanelController controller) {
        this.controller = controller;
        initComponents();
        setupTable();
        makeTableReadOnly();   
        loadAppointmentsAndFilters();
        updateField();
    }

    private void cancelAppointment(){
        String id = AppointmentIDSelection.getSelectedItem().toString();
        String doctor = doctorField.getText();
        if(id.equals("Select Appointment")){ 
            JOptionPane.showMessageDialog(this, "Please select a record to cancel.", "Done", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Cancel appointment " + id + " with Doctor " + doctor + "?",
                "Confirm Cancel",
                JOptionPane.YES_NO_OPTION
        );
        if (confirm != JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,
                    "Appointment not cancelled.",
                    "Info", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        //model.setValueAt("Cancelled", row, 4);
        try {
            customerAppt.cancelAppointment(id);
            JOptionPane.showMessageDialog(this, "Appointment " + id + " cancelled successfully.", "Done", JOptionPane.INFORMATION_MESSAGE);

            // refresh the dropdown and the table to reflect the cancellation
            loadAppointmentsAndFilters();
            setupTable();
            updateField();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cancellation unsuccessful: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private String doctorNameById(String doctorId) {
        for (Doctor d : doctorService.doctors()) {
            if (d.getSystemId().equals(doctorId)) return d.getName();
        }
        return "(unknown)";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AppointmentIDSelection = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppoinmentsRecordTable = new javax.swing.JTable();
        CancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        timeField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        doctorField = new javax.swing.JTextField();
        CancelAppointment = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(245, 243, 238));

        jLabel3.setText("Appointment ID:");

        AppointmentIDSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Appointment", " " }));
        AppointmentIDSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentIDSelectionActionPerformed(evt);
            }
        });

        AppoinmentsRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Time", "Doctor ID", "Status"
            }
        ));
        jScrollPane1.setViewportView(AppoinmentsRecordTable);

        CancelButton.setBackground(new java.awt.Color(255, 51, 51));
        CancelButton.setText("Cancel Selected Appointment");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        jLabel6.setText("Time:");

        jLabel7.setText("Type:");

        jLabel8.setText("Doctor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppointmentIDSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doctorField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AppointmentIDSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(doctorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        CancelButton.setName("contentSecondary");
        dateField.setEditable(false);
        timeField.setEditable(false);
        typeField.setEditable(false);
        doctorField.setEditable(false);

        CancelAppointment.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CancelAppointment.setText("Cancel Appointment");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelAppointment)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setName("contentSecondary");
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        cancelAppointment();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        controller.show("home");
    }//GEN-LAST:event_backBtnActionPerformed

    private void AppointmentIDSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentIDSelectionActionPerformed
        // TODO add your handling code here:
        updateField();
    }//GEN-LAST:event_AppointmentIDSelectionActionPerformed

    private void makeTableReadOnly() {
        AppoinmentsRecordTable.setDefaultEditor(Object.class, null);
    }
    
    private void loadAppointmentsAndFilters() {
        List<String> appointmentList = new ArrayList<>();
        appointmentList.add("Select Appointment");
        
        List<Appointment> list = customerAppt.myAppointments(Session.getCurrentUser().getSystemId());
        for (Appointment a : list) {
            if (a.getStatus() == Appointment.Status.SCHEDULED) {
                appointmentList.add(a.getAppointmentId());
            }
        }
        Utils.updateComboBox(AppointmentIDSelection, appointmentList);
    }
    private void updateField(){
        String id = AppointmentIDSelection.getSelectedItem().toString();
        if(id.equals("Select Appointment")){
            doctorField.setText("---");
            typeField.setText("---");
            dateField.setText("---");
            timeField.setText("---");
        }
        else{
            Appointment selected = customerAppt.getAppointment(id);
            doctorField.setText(doctorNameById(selected.getDoctorId()));
            typeField.setText(selected.getType().toString());
            dateField.setText(selected.getDate());
            timeField.setText(selected.getTime());
        }
    }
    private void setupTable(){
        List<Appointment> appointments = customerAppt.myAppointments(Session.getCurrentUser().getSystemId());
        List<Appointment> filter = new ArrayList<>();
        for(Appointment a: appointments){
            if(a.getStatus().equals(Appointment.Status.SCHEDULED)){
                filter.add(a);
            }
        }
        Utils.refreshTable(AppoinmentsRecordTable,filter,a -> new Object[] {
                a.getAppointmentId(),
                a.getDate(),
                a.getTime(),
                doctorNameById(a.getDoctorId()),
                a.getStatus()
            }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppoinmentsRecordTable;
    private javax.swing.JComboBox<String> AppointmentIDSelection;
    private javax.swing.JLabel CancelAppointment;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField doctorField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField timeField;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
