package javaproj.GUI.Customer;
import javaproj.GUI.Credentials.Session;
import javaproj.Methods.Feedback.CustomerFeedback;
import javaproj.Repository.AppointmentRepository;
import javaproj.Repository.FeedbackRepository;
import javaproj.Methods.User.CustomerService;
import javaproj.Utils.PanelController;
import javaproj.Utils.Utils;
import javax.swing.JOptionPane;
public class ProvideCommentPanel extends javax.swing.JPanel {
    private PanelController controller;
    private final FeedbackRepository feedbackRepo = new FeedbackRepository();
    private final AppointmentRepository apptRepo = new AppointmentRepository();
    private final CustomerService customerService = new CustomerService();
    private final CustomerFeedback customerFeedback = new CustomerFeedback(feedbackRepo, apptRepo, customerService);
    
    public ProvideCommentPanel(PanelController controller) {
        this.controller = controller;
        initComponents();
        loadAppointments();
    }
    public void setVisible(boolean flag) {
        super.setVisible(flag);
            if (flag) {
                loadAppointments();
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Comment1 = new javax.swing.JLabel();
        SubmitComment = new javax.swing.JButton();
        AppointmentID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Comment2 = new javax.swing.JLabel();
        SecondComment = new javax.swing.JTextField();
        FirstComment = new javax.swing.JTextField();
        Comments = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ratingSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(245, 243, 238));

        Comment1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Comment1.setText("Comment for the Doctor: ");

        SubmitComment.setBackground(new java.awt.Color(102, 204, 255));
        SubmitComment.setText("Submit");
        SubmitComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitCommentActionPerformed(evt);
            }
        });

        AppointmentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Choose Appointment ID");

        Comment2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Comment2.setText("Comment for the Staff:");

        FirstComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstCommentActionPerformed(evt);
            }
        });

        Comments.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Comments.setText("Provide Comment / Feedback");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Overall Service Rating:");

        ratingSlider.setMajorTickSpacing(1);
        ratingSlider.setMaximum(5);
        ratingSlider.setMinimum(1);
        ratingSlider.setMinorTickSpacing(1);
        ratingSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ratingSliderStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SecondComment, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                .addComponent(FirstComment)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Comment1)
                                        .addComponent(jLabel4)
                                        .addComponent(Comment2))
                                    .addGap(127, 127, 127)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AppointmentID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Comments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitComment, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Comments, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comment1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstComment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comment2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondComment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ratingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubmitComment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        SubmitComment.setName("contentSecondary");
        ratingSlider.setValue(3);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel2.setName("contentSecondary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitCommentActionPerformed
        // TODO add your handling code here: 
        String comment1 = FirstComment.getText().trim();
        String comment2 = SecondComment.getText().trim();
        String appointmentId = AppointmentID.getSelectedItem().toString().split("-")[0];
        String userType = "CUSTOMER";
        String rating = String.valueOf(ratingSlider.getValue());

        if (appointmentId == null || comment1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select appointment, person and enter a comment.");
            return;
        }
        else{
            JOptionPane.showMessageDialog(this, "Comment given.");
        }
        customerFeedback.submit(appointmentId, rating, comment1, comment2);
        refresh();
    }//GEN-LAST:event_SubmitCommentActionPerformed

    
    private void ratingSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ratingSliderStateChanged
        // TODO add your handling code here:
        jLabel2.setText(String.valueOf(ratingSlider.getValue()));
    }//GEN-LAST:event_ratingSliderStateChanged

    private void FirstCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstCommentActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        controller.show("home");
    }//GEN-LAST:event_backBtnActionPerformed

    private void loadAppointments() {
        Utils.updateComboBox(AppointmentID,customerFeedback.pendingAppointmentIds(Session.getCurrentUser().getSystemId()));

    }

    private void refresh(){
        loadAppointments();
        FirstComment.setText("");
        SecondComment.setText("");
        ratingSlider.setValue(3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AppointmentID;
    private javax.swing.JLabel Comment1;
    private javax.swing.JLabel Comment2;
    private javax.swing.JLabel Comments;
    private javax.swing.JTextField FirstComment;
    private javax.swing.JTextField SecondComment;
    private javax.swing.JButton SubmitComment;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider ratingSlider;
    // End of variables declaration//GEN-END:variables
}
