/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproj.GUI.Customer;

/**
 *
 * @author user
 */

import java.util.*;
import javaproj.GUI.Credentials.Session;
import javaproj.Model.*;
import javaproj.Methods.User.DoctorService;
import javaproj.Methods.User.StaffService;
import javaproj.Repository.AppointmentRepository;
import javaproj.Methods.Appointment.CustomerAppointment;
import javaproj.Repository.FeedbackRepository;
import javaproj.Methods.Feedback.CustomerFeedback;
import javaproj.Methods.User.CustomerService;
import javaproj.Utils.PanelController;
import javaproj.Utils.Utils;
import javaproj.Methods.Payment.CustomerPayment;
import javaproj.Repository.PaymentRepository;

public class ViewHistoryPanel extends javax.swing.JPanel {
    
    private PanelController controller;
    private final AppointmentRepository apptRepo = new AppointmentRepository();
    private final CustomerAppointment customerAppt = new CustomerAppointment(apptRepo);
    private final PaymentRepository paymentRepo = new PaymentRepository();
    private final CustomerPayment customerPayment = new CustomerPayment(paymentRepo, apptRepo);
    private final FeedbackRepository feedbackRepo = new FeedbackRepository();
    private final CustomerService customerService = new CustomerService();
    private final CustomerFeedback customerFeedback = new CustomerFeedback(feedbackRepo, apptRepo, customerService);


    // New per-role services
    private final StaffService  staffService  = new StaffService();
    private final DoctorService doctorService = new DoctorService();
    
    private Map<String, String> staffMap  = Collections.emptyMap();
    private Map<String, String> doctorMap = Collections.emptyMap();
    
    public ViewHistoryPanel(PanelController controller) {
        this.controller = controller;
        initComponents();
        rebuildNameMaps();
        loadTableFromFile();
    }
    @Override
    public void setVisible(boolean flag) {
        super.setVisible(flag);
        if (flag) {
            loadTableFromFile();
        }
    }
    private void rebuildNameMaps() {
        Map<String,String> sMap = new LinkedHashMap<>();
        for (var s : staffService.list()) {              // adjust to your method name
            sMap.put(s.getSystemId(), s.getName());
        }
        Map<String,String> dMap = new LinkedHashMap<>();
        for (var d : doctorService.doctors()) {
            dMap.put(d.getSystemId(), d.getName());
        }
        staffMap  = sMap;
        doctorMap = dMap;
    }
    private void loadTableFromFile(){
        //appointment
        var userId = Session.getCurrentUser().getSystemId();
        List<Appointment> appointments = customerAppt.myAppointments(userId);
        Utils.refreshTable(appointmentTable, appointments, a -> new Object[] {
            a.getAppointmentId(),
            staffMap.getOrDefault(a.getStaffId(),  "(unknown)"),
            doctorMap.getOrDefault(a.getDoctorId(), "(unknown)"),
            a.getDate(),
            a.getTime(),
            a.getStatus(),
            a.getType()
        });
        //payment
        String currentCustomerId = Session.getCurrentUser().getSystemId();
        List<Payment> payments = customerPayment.myPayments(currentCustomerId);
        Utils.refreshTable(paymentTable, payments, p -> new Object[] {
            p.getPaymentId(),
            p.getAppointmentId(),
            p.getDate(),
            p.getTime(),
            p.getAmount(),
            p.getStatus()
        });
        //feeback
        List<Feedback> feedbacks = customerFeedback.feedbackByCustomer(Session.getCurrentUser().getSystemId());
        Utils.refreshTable(feedbackTable, feedbacks, f -> new Object[] {
            f.getFeedbackId(),
            f.getAppointmentId(),
            f.getRating(),
            f.getComment1(),
            f.getComment2()
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Staff", "Doctor", "Date", "Time", "Status", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(appointmentTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Appointments", jPanel1);

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Payment ID", "Appointment ID", "Date", "Time", "Amount(RM)", "Status"
            }
        ));
        jScrollPane2.setViewportView(paymentTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Payments", jPanel2);

        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Feedback ID", "Appointment ID", "Ratings", "Comment for Doctor", "Comment for Staff"
            }
        ));
        jScrollPane4.setViewportView(feedbackTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Feedbacks", jPanel5);

        jLabel1.setText("View History");
        jLabel1.setAutoscrolls(true);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        controller.show("home");
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable paymentTable;
    // End of variables declaration//GEN-END:variables
}
