package javaproj.GUI.Credentials;

import javaproj.Methods.User.SuperManagerService;
import javaproj.Methods.User.CustomerService;
import javaproj.Methods.User.StaffService;
import javaproj.Methods.User.DoctorService;
import javaproj.Methods.User.ManagerService;
import javaproj.Model.Role.*;

import javax.swing.JOptionPane;
import java.util.*;

public class ForgotPassword extends javax.swing.JFrame {

    private final CustomerService customerSvc   = new CustomerService();
    private final DoctorService   doctorSvc     = new DoctorService();
    private final StaffService    staffSvc      = new StaffService();
    private final ManagerService  managerSvc    = new ManagerService();
    private final SuperManagerService superMgrSvc = new SuperManagerService();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }
    
    private List<User> allUsersAcrossRoles() {
        List<User> all = new ArrayList<>();
        all.addAll(customerSvc.list());
        all.addAll(doctorSvc.list());
        all.addAll(staffSvc.list());
        all.addAll(managerSvc.list());
        all.addAll(superMgrSvc.list());
        return all;
    }
    private User authenticate(String email, String ic) {
        if (email == null || ic == null) return null;
        String em = email.trim();
        String idc = ic.trim();
        if (em.isEmpty() || idc.isEmpty()) return null;

        for (User u : allUsersAcrossRoles()) {
            String uEmail = u.getEmail();
            String uIc    = u.getIdentityNumber();
            if (uEmail != null && uIc != null
                && uEmail.equalsIgnoreCase(em)
                && uIc.equals(idc)) {
                return u;
            }
        }
        return null;
    }
    private boolean resetPasswordFor(User user, String newPassword) {
        if (user instanceof Customer)     return customerSvc.resetPassword(user, newPassword);
        if (user instanceof Doctor)       return doctorSvc.resetPassword(user, newPassword);
        if (user instanceof Staff)        return staffSvc.resetPassword(user, newPassword);
        if (user instanceof Manager)      return managerSvc.resetPassword(user, newPassword);
        if (user instanceof Supermanager) return superMgrSvc.resetPassword(user, newPassword);
        return false;
    }
    private boolean basicInputValid(String ic, String email, String password) {
        if (ic == null || ic.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your IC number.");
            return false;
        }
        if (!ic.trim().matches("\\d{12}")) {
            JOptionPane.showMessageDialog(this, "IC number must be exactly 12 digits.");
            return false;
        }
        if (email == null || email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email.");
            return false;
        }
        if (password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a new password.");
            return false;
        }
        return true;
    }
    private void forgetPassword() {
        String ic       = ICNumtxtFieldReg.getText();
        String email    = EmailtxtFieldReg.getText();
        String password = new String(pwdtxtFieldReg.getPassword());

        if (!basicInputValid(ic, email, password)) return;

        User user = authenticate(email, ic);
        if (user == null) {
            JOptionPane.showMessageDialog(this, "User not found. Please check your IC and Email.");
            return;
        }

        boolean ok = resetPasswordFor(user, password.trim());
        if (ok) {
            JOptionPane.showMessageDialog(this, "Password updated successfully.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update password. Please try again.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pwdCheckReg = new javax.swing.JCheckBox();
        EmailtxtFieldReg = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        lblICNumReg = new javax.swing.JLabel();
        pwdtxtFieldReg = new javax.swing.JPasswordField();
        ICNumtxtFieldReg = new javax.swing.JTextField();
        lblPasswordReg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmailReg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        pwdCheckReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        pwdCheckReg.setText("Show Password");
        pwdCheckReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdCheckRegActionPerformed(evt);
            }
        });

        EmailtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        btnSignUp.setBackground(new java.awt.Color(4, 110, 130));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Reset");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblICNumReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblICNumReg.setText("IC Number *");

        pwdtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        pwdtxtFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtxtFieldRegActionPerformed(evt);
            }
        });

        ICNumtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        lblPasswordReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPasswordReg.setText("New Password *");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forget Password");

        lblEmailReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblEmailReg.setText("Email Address *");

        jLabel2.setText("Please enter you basic information to reset your password.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdCheckReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPasswordReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblICNumReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ICNumtxtFieldReg)
                    .addComponent(EmailtxtFieldReg)
                    .addComponent(pwdtxtFieldReg)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblICNumReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ICNumtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailReg)
                .addGap(6, 6, 6)
                .addComponent(EmailtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordReg)
                .addGap(6, 6, 6)
                .addComponent(pwdtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdCheckReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignUp)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnSignUp.setName("contentSecondary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdCheckRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdCheckRegActionPerformed
        if (pwdCheckReg.isSelected()){
            pwdtxtFieldReg.setEchoChar((char)0);
        } else{
            pwdtxtFieldReg.setEchoChar('●');
        }
    }//GEN-LAST:event_pwdCheckRegActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        forgetPassword();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void pwdtxtFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtxtFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtxtFieldRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailtxtFieldReg;
    private javax.swing.JTextField ICNumtxtFieldReg;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmailReg;
    private javax.swing.JLabel lblICNumReg;
    private javax.swing.JLabel lblPasswordReg;
    private javax.swing.JCheckBox pwdCheckReg;
    private javax.swing.JPasswordField pwdtxtFieldReg;
    // End of variables declaration//GEN-END:variables
}
