package javaproj.GUI.Credentials;

import javaproj.Methods.Parser.StaffParser;
import javaproj.Methods.Parser.CustomerParser;
import javaproj.Methods.Parser.DoctorParser;
import javaproj.Methods.Parser.SupermanagerParser;
import javaproj.Methods.Parser.ManagerParser;
import java.awt.*;
import javaproj.GUI.Customer.CustomerFrame;
import javaproj.Model.Role.*;
import javaproj.GUI.Doctors.DoctorFrame;
import javaproj.GUI.Manager.ManagerFrame;
import javaproj.GUI.Staff.StaffFrame;
import javax.swing.*;
import javaproj.Utils.*;

public class LoginPanel extends javax.swing.JPanel {

    private JPanel contentPanel;
    private PanelController controller;
    
    public LoginPanel(PanelController controller) {
        this.controller = controller;
        initComponents();
        
        // Initialize default login pwd echo char
        pwdtxtField.setEchoChar('●');
        
        // Set the label to cursor on hover
        lbllinkForgot.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lbllinkSignUp.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginFeilds = new javax.swing.JPanel();
        lbllinkSignUp = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pwdtxtField = new javax.swing.JPasswordField();
        EmailtxtField = new javax.swing.JTextField();
        btnSignIn = new javax.swing.JButton();
        pwdCheck = new javax.swing.JCheckBox();
        lbllinkForgot = new javax.swing.JLabel();
        changeTheme = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pictureFormat1 = new javaproj.Comp.PictureFormat();

        LoginFeilds.setBackground(java.awt.Color.white);

        lbllinkSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbllinkSignUp.setForeground(new java.awt.Color(0, 102, 204));
        lbllinkSignUp.setText("Sign up");
        lbllinkSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllinkSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllinkSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllinkSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllinkSignUpMouseExited(evt);
            }
        });

        lblAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAccount.setForeground(java.awt.Color.black);
        lblAccount.setText("Don't have an account?");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setForeground(java.awt.Color.black);
        lblEmail.setText("Email Address");

        lblPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblPassword.setForeground(java.awt.Color.black);
        lblPassword.setText("Password");

        pwdtxtField.setBackground(new java.awt.Color(217, 217, 217));
        pwdtxtField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmailtxtField.setBackground(new java.awt.Color(217, 217, 217));
        EmailtxtField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSignIn.setBackground(new java.awt.Color(4, 110, 130));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setText("Sign in");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        pwdCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pwdCheck.setForeground(java.awt.Color.black);
        pwdCheck.setText("Show Password");
        pwdCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdCheckActionPerformed(evt);
            }
        });

        lbllinkForgot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbllinkForgot.setForeground(new java.awt.Color(0, 102, 204));
        lbllinkForgot.setText("Forgot Password?");
        lbllinkForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllinkForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllinkForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllinkForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllinkForgotMouseExited(evt);
            }
        });

        changeTheme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeTheme.setForeground(new java.awt.Color(0, 102, 204));
        changeTheme.setText("Change Theme");
        changeTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeThemeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeThemeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changeThemeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginFeildsLayout = new javax.swing.GroupLayout(LoginFeilds);
        LoginFeilds.setLayout(LoginFeildsLayout);
        LoginFeildsLayout.setHorizontalGroup(
            LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFeildsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginFeildsLayout.createSequentialGroup()
                        .addComponent(pwdCheck)
                        .addGap(56, 56, 56)
                        .addComponent(lbllinkForgot))
                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginFeildsLayout.createSequentialGroup()
                        .addGroup(LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginFeildsLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFeildsLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(changeTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(lbllinkSignUp)))
                .addGap(40, 40, 40))
        );
        LoginFeildsLayout.setVerticalGroup(
            LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFeildsLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(lblEmail)
                .addGap(6, 6, 6)
                .addComponent(EmailtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblPassword)
                .addGap(6, 6, 6)
                .addComponent(pwdtxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdCheck)
                    .addGroup(LoginFeildsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbllinkForgot)))
                .addGap(18, 18, 18)
                .addComponent(btnSignIn)
                .addGap(18, 18, 18)
                .addGroup(LoginFeildsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccount)
                    .addComponent(lbllinkSignUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(changeTheme)
                .addContainerGap())
        );

        lbllinkSignUp.setName("blue");
        btnSignIn.setName("contentSecondary");
        lbllinkForgot.setName("blue");
        changeTheme.setName("blue");

        jPanel1.setBackground(new java.awt.Color(245, 243, 238));

        pictureFormat1.set$image(new javax.swing.ImageIcon(getClass().getResource("/javaproj/image/AMC logo & text.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(pictureFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(LoginFeilds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginFeilds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.setName("contentSecondary");
    }// </editor-fold>//GEN-END:initComponents

    private void lbllinkSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignUpMouseClicked
//        controller.show("signUp");
        SignUpFrame signUp = new SignUpFrame();
        signUp.setVisible(true);
    }//GEN-LAST:event_lbllinkSignUpMouseClicked

    private void lbllinkSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignUpMouseEntered
        lbllinkSignUp.setForeground(new Color(0,51,204));
    }//GEN-LAST:event_lbllinkSignUpMouseEntered

    private void lbllinkSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignUpMouseExited
        lbllinkSignUp.setForeground(new Color(0,102,204));
    }//GEN-LAST:event_lbllinkSignUpMouseExited

    private void pwdCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdCheckActionPerformed
        if (pwdCheck.isSelected()){
            pwdtxtField.setEchoChar((char)0);
        } else{
            pwdtxtField.setEchoChar('●');
        }
    }//GEN-LAST:event_pwdCheckActionPerformed

    private void lbllinkForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkForgotMouseClicked
        ForgotPassword forgot = new ForgotPassword();
        forgot.setVisible(true);
    }//GEN-LAST:event_lbllinkForgotMouseClicked

    private void lbllinkForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkForgotMouseEntered
        lbllinkForgot.setForeground(new Color(0,51,204));
    }//GEN-LAST:event_lbllinkForgotMouseEntered

    private void lbllinkForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkForgotMouseExited
        lbllinkForgot.setForeground(new Color(0,102,204));
    }//GEN-LAST:event_lbllinkForgotMouseExited

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        handleLogin();
    }//GEN-LAST:event_btnSignInActionPerformed

    private void changeThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeThemeMouseClicked
        // TODO add your handling code here:
        ThemeManager.getInstance().toggleThemeAndRefreshAll();
    }//GEN-LAST:event_changeThemeMouseClicked

    private void changeThemeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeThemeMouseEntered
        // TODO add your handling code here:
        changeTheme.setForeground(new Color(0,51,204));
    }//GEN-LAST:event_changeThemeMouseEntered

    private void changeThemeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeThemeMouseExited
        // TODO add your handling code here:
        changeTheme.setForeground(new Color(0,102,204));
    }//GEN-LAST:event_changeThemeMouseExited

    private void handleLogin() {
        String email = EmailtxtField.getText().trim();
        String password = new String(pwdtxtField.getPassword());
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and password");
            return;
        }
        
        // Authenticate across all user types
        User user = authenticate(email, password);
        
        if (user != null) {
            Session.setCurrentUser(user);
            JFrame next = null;
            JOptionPane.showMessageDialog(this, "Welcome " + user.getName() + "! Role: " + Session.getUserRole());

            
            // Redirect based on role
            if (user instanceof Customer) {
                next = new CustomerFrame((Customer) user);
            } else if (user instanceof Manager) {
                next = new ManagerFrame((Manager) user);
            } else if (user instanceof Doctor) {
                next = new DoctorFrame((Doctor) user);
            } else if (user instanceof Staff) {
                next = new StaffFrame((Staff) user);
            }
            next.setLocationRelativeTo(null);
            next.setVisible(true);
            
            java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (w != null) {
                w.setVisible(false);
                w.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid email or password");
        }
        
    }
    
    private User authenticate(String email, String password) {
        // Customers
        for (Customer c : Utils.readFile("data/Customer.txt", new CustomerParser())) {
            if (c.getEmail().equalsIgnoreCase(email) && c.getPassword().equals(password)) {
                return c;
            }
        }

        // Managers
        for (Manager m : Utils.readFile("data/manager.txt", new ManagerParser())) {
            if (m.getEmail().equalsIgnoreCase(email) && m.getPassword().equals(password)) {
                return m;
            }
        }

        // Doctors
        for (Doctor d : Utils.readFile("data/doctor.txt", new DoctorParser())) {
            if (d.getEmail().equalsIgnoreCase(email) && d.getPassword().equals(password)) {
                return d;
            }
        }

        // Staff
        for (Staff s : Utils.readFile("data/staff.txt", new StaffParser())) {
            if (s.getEmail().equalsIgnoreCase(email) && s.getPassword().equals(password)) {
                return s;
            }
        }
        for (Supermanager m : Utils.readFile("data/supermanager.txt", new SupermanagerParser())){
            if (m.getEmail().equalsIgnoreCase(email) && m.getPassword().equals(password)) {
                return m;
            }
        }

        return null;
    }    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailtxtField;
    private javax.swing.JPanel LoginFeilds;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel changeTheme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lbllinkForgot;
    private javax.swing.JLabel lbllinkSignUp;
    private javaproj.Comp.PictureFormat pictureFormat1;
    private javax.swing.JCheckBox pwdCheck;
    private javax.swing.JPasswordField pwdtxtField;
    // End of variables declaration//GEN-END:variables
}
