/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproj.GUI.Credentials;

import java.awt.Color;
import javaproj.Methods.User.CheckDuplicates;
import javax.swing.JOptionPane;

import javaproj.Methods.User.CustomerService; 
/**
 *
 * @author NICK
 */
public class SignUpFrame extends javax.swing.JFrame {
    
    private final CustomerService customerSvc = new CustomerService(); 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpFrame.class.getName());
    private final CheckDuplicates checker = new CheckDuplicates();

    private void signUp(){
        String name, ic, email, phone, address, password, passwordR;
        name = PatientNametxtFieldReg.getText();
        ic = ICNumtxtFieldReg.getText();
        email = EmailtxtFieldReg.getText();
        phone = PhoneNumtxtFieldReg.getText();
        address =txtFieldHomeAddress.getText();
        password = new String(pwdtxtFieldReg.getPassword()).trim();
        passwordR  = new String(conpwdtxtFieldReg.getPassword()).trim();
        
        if (password.isEmpty() || passwordR.isEmpty() || !password.equals(passwordR)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Password Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String fieldError = customerSvc.validateForm(name, ic, address, phone, email);
        if (fieldError != null) {
            JOptionPane.showMessageDialog(this, fieldError,
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
       String dup = checker.checkDuplicates(null,ic, email);
        if (dup != null) {
            JOptionPane.showMessageDialog(this, dup,
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        customerSvc.signup(name, ic, address, phone, email, password);
        
        JOptionPane.showMessageDialog(this, "Sign up successfully!");
        this.dispose();
    }
    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFieldHomeAddress = new javax.swing.JTextField();
        lblConPasswordReg = new javax.swing.JLabel();
        pwdCheckReg = new javax.swing.JCheckBox();
        conpwdtxtFieldReg = new javax.swing.JPasswordField();
        ConpwdCheckReg = new javax.swing.JCheckBox();
        EmailtxtFieldReg = new javax.swing.JTextField();
        lbllinkSignIn = new javax.swing.JLabel();
        lblPNameReg = new javax.swing.JLabel();
        lblAccountSignIn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPhoneNumReg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        PatientNametxtFieldReg = new javax.swing.JTextField();
        lblICNumReg = new javax.swing.JLabel();
        pwdtxtFieldReg = new javax.swing.JPasswordField();
        ICNumtxtFieldReg = new javax.swing.JTextField();
        lblPasswordReg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PhoneNumtxtFieldReg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        lblEmailReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblConPasswordReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblConPasswordReg.setText("Confirm Password *");

        pwdCheckReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        pwdCheckReg.setText("Show Password");
        pwdCheckReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdCheckRegActionPerformed(evt);
            }
        });

        conpwdtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        ConpwdCheckReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ConpwdCheckReg.setText("Show Password");
        ConpwdCheckReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConpwdCheckRegActionPerformed(evt);
            }
        });

        EmailtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        lbllinkSignIn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbllinkSignIn.setForeground(new java.awt.Color(0, 102, 204));
        lbllinkSignIn.setText("Sign In here");
        lbllinkSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllinkSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllinkSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllinkSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllinkSignInMouseExited(evt);
            }
        });

        lblPNameReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPNameReg.setText("Full Name *");

        lblAccountSignIn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAccountSignIn.setText("Already have an account?");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Please fill in all required information to register");

        lblPhoneNumReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPhoneNumReg.setText("Phone Number *");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Personal Information");

        btnSignUp.setBackground(new java.awt.Color(4, 110, 130));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        PatientNametxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        lblICNumReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblICNumReg.setText("IC Number *");

        pwdtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        pwdtxtFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtxtFieldRegActionPerformed(evt);
            }
        });

        ICNumtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        lblPasswordReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPasswordReg.setText("Password *");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Contact Information");

        PhoneNumtxtFieldReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Registration");

        lblHomeAddress.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblHomeAddress.setText("Home Address *");

        lblEmailReg.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblEmailReg.setText("Email Address *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFieldHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblEmailReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EmailtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PhoneNumtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPhoneNumReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(pwdCheckReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pwdtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblConPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ConpwdCheckReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(conpwdtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(205, 205, 205)
                                            .addComponent(lblAccountSignIn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbllinkSignIn)))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPNameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(lblICNumReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(PatientNametxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(ICNumtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPNameReg)
                    .addComponent(lblICNumReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientNametxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ICNumtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailReg)
                    .addComponent(lblPhoneNumReg))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNumtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHomeAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasswordReg)
                    .addComponent(lblConPasswordReg))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conpwdtxtFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdCheckReg)
                    .addComponent(ConpwdCheckReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllinkSignIn)
                    .addComponent(lblAccountSignIn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbllinkSignIn.setName("blue");
        btnSignUp.setName("contentSecondary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdCheckRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdCheckRegActionPerformed
        if (pwdCheckReg.isSelected()){
            pwdtxtFieldReg.setEchoChar((char)0);
        } else{
            pwdtxtFieldReg.setEchoChar('●');
        }
    }//GEN-LAST:event_pwdCheckRegActionPerformed

    private void ConpwdCheckRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConpwdCheckRegActionPerformed
        if (ConpwdCheckReg.isSelected()){
            conpwdtxtFieldReg.setEchoChar((char)0);
        } else{
            conpwdtxtFieldReg.setEchoChar('●');
        }
    }//GEN-LAST:event_ConpwdCheckRegActionPerformed

    private void lbllinkSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignInMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbllinkSignInMouseClicked

    private void lbllinkSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignInMouseEntered
        lbllinkSignIn.setForeground(new Color(0,51,204));
    }//GEN-LAST:event_lbllinkSignInMouseEntered

    private void lbllinkSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllinkSignInMouseExited
        lbllinkSignIn.setForeground(new Color(0,102,204));
    }//GEN-LAST:event_lbllinkSignInMouseExited

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        signUp();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void pwdtxtFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtxtFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtxtFieldRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ConpwdCheckReg;
    private javax.swing.JTextField EmailtxtFieldReg;
    private javax.swing.JTextField ICNumtxtFieldReg;
    private javax.swing.JTextField PatientNametxtFieldReg;
    private javax.swing.JTextField PhoneNumtxtFieldReg;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPasswordField conpwdtxtFieldReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAccountSignIn;
    private javax.swing.JLabel lblConPasswordReg;
    private javax.swing.JLabel lblEmailReg;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblICNumReg;
    private javax.swing.JLabel lblPNameReg;
    private javax.swing.JLabel lblPasswordReg;
    private javax.swing.JLabel lblPhoneNumReg;
    private javax.swing.JLabel lbllinkSignIn;
    private javax.swing.JCheckBox pwdCheckReg;
    private javax.swing.JPasswordField pwdtxtFieldReg;
    private javax.swing.JTextField txtFieldHomeAddress;
    // End of variables declaration//GEN-END:variables
}
