package javaproj.GUI.Doctors;


import java.awt.*;
import javaproj.GUI.Credentials.LoginFrame;
import javaproj.GUI.Credentials.Session;
import javaproj.GUI.Common.*;
import javaproj.Model.Role.Doctor;
import javaproj.Utils.*;
import javax.swing.*;

public class DoctorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorFrame.class.getName());

    private CardLayout cardLayout;
    private JPanel contentPanel;
    
    //NAVBAR
    private DrHomePanel drhomePanel;
    private ProfilePanel drprofilePanel;
    private SettingPanel drsettingPanel;
    private AboutUsPanel aboutUsPanel;
    
    private DrAppointment drappointment;
    private PatientHistory patienthistory;
    private DrViewComments drviewcomments;
    private DrFeedback drfeedback;
    private ChargePanel chargepanel;

    //Logged-in doctor
    private Doctor loggedInDoctor;
    
    public DoctorFrame(Doctor doctor) {
        this.loggedInDoctor = doctor;  //save doctor info
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);        
        setSize(1024,768);
        setLocationRelativeTo(null); // Center frame
        
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        PanelController controller = new PanelController(contentPanel);
        
        //NAVBAR PANEL BUTTON
        drhomePanel = new DrHomePanel(controller,loggedInDoctor);
        drprofilePanel = new ProfilePanel();
        drsettingPanel = new SettingPanel();
        aboutUsPanel = new AboutUsPanel();
        drappointment = new DrAppointment(loggedInDoctor,controller);
        patienthistory = new PatientHistory(loggedInDoctor,controller);
        drviewcomments = new DrViewComments(loggedInDoctor,controller);
        drfeedback = new DrFeedback(loggedInDoctor,controller);
        chargepanel = new ChargePanel(loggedInDoctor,controller);
        
        contentPanel.add(drhomePanel, "home");
        contentPanel.add(drprofilePanel, "profile");
        contentPanel.add(drsettingPanel, "setting");
        contentPanel.add(aboutUsPanel, "aboutUs");
        contentPanel.add(drappointment, "appointment");
        contentPanel.add(chargepanel, "charge");
        contentPanel.add(drviewcomments, "view comments");
        contentPanel.add(drfeedback, "feedback");
        contentPanel.add(patienthistory, "patient history");
        

        
        
        //HOME PANEL BUTTON
//        makeAppointmentPanel = new MakeAppointmentPanel();
//        customerPanel = new CustomerPanel(controller);
//        paymentPanel = new PaymentPanel();
//        appointmentRecordPanel = new AppointmentRecordPanel();
        
//        drcontentPanel.add(makeAppointmentPanel, "makeAppointment");
//        drcontentPanel.add(customerPanel, "customer");
//        drcontentPanel.add(paymentPanel,"payment");
//        drcontentPanel.add(appointmentRecordPanel,"appointmentRecord");
        
        

        // Layout main window
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jPanel1, BorderLayout.NORTH);       // Top bar
        getContentPane().add(contentPanel, BorderLayout.CENTER); // Main content

        // Initial page
        cardLayout.show(contentPanel, "home");
    }
    
    public DoctorFrame() {
        this(null); // calls the other constructor with null
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        pictureFormat1 = new javaproj.Comp.PictureFormat();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 243, 238));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnSetting.setText("Setting");
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });

        btnAboutUs.setText("About Us");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        pictureFormat1.set$image(new javax.swing.ImageIcon(getClass().getResource("/javaproj/image/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pictureFormat1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(pictureFormat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 297, Short.MAX_VALUE))
        );

        jPanel1.setName("contentSecondary");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "home");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Session.clear();
        JFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "profile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "setting");
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "aboutUs");
    }//GEN-LAST:event_btnAboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DoctorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSetting;
    private javax.swing.JPanel jPanel1;
    private javaproj.Comp.PictureFormat pictureFormat1;
    // End of variables declaration//GEN-END:variables
}
