package javaproj.GUI.Doctors;

import javaproj.Model.Role.*;
import javaproj.Model.*;

import javax.swing.*;
import java.util.*;
import javaproj.Repository.AppointmentRepository;
import javaproj.Methods.Appointment.DoctorAppointment;
import javaproj.Methods.Feedback.DoctorFeedback;
import javaproj.Repository.FeedbackRepository;
import javaproj.Methods.User.CustomerService;

import javaproj.Utils.PanelController;
import javaproj.Utils.Utils;

public class DrFeedback extends javax.swing.JPanel {

    private Doctor doctor;
    private PanelController controller;
    private List<Appointment> appointments;
    private List<Customer> customers;
    private List<Feedback> feedback;
    private final AppointmentRepository apptRepo = new AppointmentRepository();
    private final DoctorAppointment doctorAppt   = new DoctorAppointment(apptRepo);
    private final FeedbackRepository feedbackRepo = new FeedbackRepository();
    private final DoctorFeedback doctorFeedback = new DoctorFeedback(feedbackRepo, apptRepo, new CustomerService());

    
    public DrFeedback(Doctor doctor, PanelController controller) {
        this.controller = controller;
        this.doctor = doctor;
        initComponents();
        btnSave.addActionListener(e -> saveFeedback());
        loadAppointments();
    }
    public void setVisible(boolean flag) {
        super.setVisible(flag);
            if (flag) {
                loadAppointments();
            }
        }
    
    private void loadAppointments() {
        appointments = doctorAppt.appointmentList(doctor.getSystemId());

        feedback = feedbackRepo.findAll();

        Set<String> alreadyGiven = new HashSet<>();
        for (Feedback f : feedback) {
            if ("DOCTOR".equalsIgnoreCase(f.getUserType())) {
                alreadyGiven.add(f.getAppointmentId());
            }
        }

        List<String> comboItems = new ArrayList<>();
        for (Appointment a : appointments) {
            if (a.getStatus() == Appointment.Status.COMPLETED && !alreadyGiven.contains(a.getAppointmentId())) {
                comboItems.add(a.getAppointmentId() + " - " + a.getDate() + " " + a.getTime() + " - " + a.getCustomerId());
            }
        }

        Utils.updateComboBox(cmbAppt, comboItems);

    }
    
    private void saveFeedback() {
        String selected = (String) cmbAppt.getSelectedItem();
        if (selected == null || selected.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment.");
            return;
        }

        String appointmentId = selected.split(" - ")[0];
        String comment = txtComment.getText().trim();

        if (comment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a comment.");
            return;
        }
        doctorFeedback.submit(appointmentId, null, comment, null);
        JOptionPane.showMessageDialog(this, "Feedback saved successfully!");

        // Clear input
        txtComment.setText("");

        // Refresh combo box so this appointment disappears
        loadAppointments();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        lblAppt = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        cmbAppt = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setText("Save");

        lblAppt.setText("Select Appointment:");

        lblComment.setText("Doctor Feedback:");

        cmbAppt.setModel(new javax.swing.DefaultComboBoxModel<>());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Feedback");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblComment)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAppt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbAppt, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppt)
                    .addComponent(cmbAppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblComment)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        controller.show("home");
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAppt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppt;
    private javax.swing.JLabel lblComment;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
